import { IPatientDashboard } from '@core/models/patients/patientModel';

export const risks = [1, 2, 3];

export const top100Films = [
  { title: 'The Shawshank Redemption', year: 1994 },
  { title: 'The Godfather', year: 1972 },
  { title: 'The Godfather: Part II', year: 1974 },
  { title: 'The Dark Knight', year: 2008 },
  { title: '12 Angry Men', year: 1957 },
  { title: "Schindler's List", year: 1993 },
  { title: 'Pulp Fiction', year: 1994 },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
  },
  { title: 'The Good, the Bad and the Ugly', year: 1966 },
  { title: 'Fight Club', year: 1999 },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
  },
  {
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    year: 1980,
  },
  { title: 'Forrest Gump', year: 1994 },
  { title: 'Inception', year: 2010 },
  {
    title: 'The Lord of the Rings: The Two Towers',
    year: 2002,
  },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
  { title: 'Goodfellas', year: 1990 },
  { title: 'The Matrix', year: 1999 },
  { title: 'Seven Samurai', year: 1954 },
  {
    title: 'Star Wars: Episode IV - A New Hope',
    year: 1977,
  },
  { title: 'City of God', year: 2002 },
  { title: 'Se7en', year: 1995 },
  { title: 'The Silence of the Lambs', year: 1991 },
  { title: "It's a Wonderful Life", year: 1946 },
  { title: 'Life Is Beautiful', year: 1997 },
  { title: 'The Usual Suspects', year: 1995 },
  { title: 'Léon: The Professional', year: 1994 },
  { title: 'Spirited Away', year: 2001 },
  { title: 'Saving Private Ryan', year: 1998 },
  { title: 'Once Upon a Time in the West', year: 1968 },
  { title: 'American History X', year: 1998 },
  { title: 'Interstellar', year: 2014 },
  { title: 'Casablanca', year: 1942 },
  { title: 'City Lights', year: 1931 },
  { title: 'Psycho', year: 1960 },
  { title: 'The Green Mile', year: 1999 },
  { title: 'The Intouchables', year: 2011 },
  { title: 'Modern Times', year: 1936 },
  { title: 'Raiders of the Lost Ark', year: 1981 },
  { title: 'Rear Window', year: 1954 },
  { title: 'The Pianist', year: 2002 },
  { title: 'The Departed', year: 2006 },
  { title: 'Terminator 2: Judgment Day', year: 1991 },
  { title: 'Back to the Future', year: 1985 },
  { title: 'Whiplash', year: 2014 },
  { title: 'Gladiator', year: 2000 },
  { title: 'Memento', year: 2000 },
  { title: 'The Prestige', year: 2006 },
  { title: 'The Lion King', year: 1994 },
  { title: 'Apocalypse Now', year: 1979 },
  { title: 'Alien', year: 1979 },
  { title: 'Sunset Boulevard', year: 1950 },
  {
    title: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    year: 1964,
  },
  { title: 'The Great Dictator', year: 1940 },
  { title: 'Cinema Paradiso', year: 1988 },
  { title: 'The Lives of Others', year: 2006 },
  { title: 'Grave of the Fireflies', year: 1988 },
  { title: 'Paths of Glory', year: 1957 },
  { title: 'Django Unchained', year: 2012 },
  { title: 'The Shining', year: 1980 },
  { title: 'WALL·E', year: 2008 },
  { title: 'American Beauty', year: 1999 },
  { title: 'The Dark Knight Rises', year: 2012 },
  { title: 'Princess Mononoke', year: 1997 },
  { title: 'Aliens', year: 1986 },
  { title: 'Oldboy', year: 2003 },
  { title: 'Once Upon a Time in America', year: 1984 },
  { title: 'Witness for the Prosecution', year: 1957 },
  { title: 'Das Boot', year: 1981 },
  { title: 'Citizen Kane', year: 1941 },
  { title: 'North by Northwest', year: 1959 },
  { title: 'Vertigo', year: 1958 },
  {
    title: 'Star Wars: Episode VI - Return of the Jedi',
    year: 1983,
  },
  { title: 'Reservoir Dogs', year: 1992 },
  { title: 'Braveheart', year: 1995 },
  { title: 'M', year: 1931 },
  { title: 'Requiem for a Dream', year: 2000 },
  { title: 'Amélie', year: 2001 },
  { title: 'A Clockwork Orange', year: 1971 },
  { title: 'Like Stars on Earth', year: 2007 },
  { title: 'Taxi Driver', year: 1976 },
  { title: 'Lawrence of Arabia', year: 1962 },
  { title: 'Double Indemnity', year: 1944 },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    year: 2004,
  },
  { title: 'Amadeus', year: 1984 },
  { title: 'To Kill a Mockingbird', year: 1962 },
  { title: 'Toy Story 3', year: 2010 },
  { title: 'Logan', year: 2017 },
  { title: 'Full Metal Jacket', year: 1987 },
  { title: 'Dangal', year: 2016 },
  { title: 'The Sting', year: 1973 },
  { title: '2001: A Space Odyssey', year: 1968 },
  { title: "Singin' in the Rain", year: 1952 },
  { title: 'Toy Story', year: 1995 },
  { title: 'Bicycle Thieves', year: 1948 },
  { title: 'The Kid', year: 1921 },
  { title: 'Inglourious Basterds', year: 2009 },
  { title: 'Snatch', year: 2000 },
  { title: '3 Idiots', year: 2009 },
  { title: 'Monty Python and the Holy Grail', year: 1975 },
];

export const patientData: IPatientDashboard = {
  Code: 'KB2200001192',
  Content: 'Health check service',
  Status: 'Inprocessing',
  FullName: 'Jillayne Pettus',
  Gender: 'Nữ',
  DOB: 1985,
  Address: 'Q7, Ho Chi Minh',
  Age: 40,
  Phone: '0988.256688',
  PhysicalCondition: {
    Height: '170 cm',
    Weight: '46 kg',
    BMI: '25.6',
    Systolic: '122',
    Diastolic: '89',
    Pulse: 90,
    Breath: 30,
    SpO2: 45,
    Temperature: 32,
  },
  Allergies: [
    {
      Id: 0,
      Name: 'Pencicilin',
      Note: 'More details ...',
      Piority: 'High',
    },
    {
      Id: 1,
      Name: 'Tilorone',
      Note: 'More details ...',
      Piority: 'Medium',
    },
  ],
  Histories: [
    {
      Id: 1,
      Name: 'Medical history 2',
      DoctorName: 'Dr. Tommy',
      CreatedOn: '10/02/2022',
    },
    {
      Id: 2,
      Name: 'Medical history 1',
      DoctorName: 'Dr. Christina Lopez',
      CreatedOn: '10/02/2022',
    },
  ],
  Risks: {
    Group: [
      { Id: 1, Content: 'affects diabetes' },
      { Id: 2, Content: 'high blood pressure' },
    ],
    Group1: [
      { Id: 1, Content: 'smoke' },
      { Id: 2, Content: 'drink alcohol' },
    ],
    Group2: [{ Id: 1, Content: 'family cancel syndronmes' }],
  },
  Symptoms: 'Chóng mặt, hoa mắt, đau vai gáy',
  DiseaseProgression: 'Ngày trước có ăn bậy, thức khuya, có uống bia',
  Diagnosis: [
    {
      Id: 1,
      IcdName: 'Disorders of choroid and retina',
      IcdCode: 'H30-H36',
      FreeText: '',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 2,
      IcdName: 'Cystic fibrosis',
      IcdCode: 'E84',
      FreeText: '',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 3,
      IcdName: 'Disorders of sphingolipid metabolism and other lipid storage disorders',
      IcdCode: 'E75',
      FreeText: '',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 4,
      IcdName: '',
      IcdCode: '',
      FreeText: 'Freetext more and more and more ...',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 5,
      IcdName: '',
      IcdCode: '',
      FreeText: 'Freetext 1',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 6,
      IcdName: '',
      IcdCode: '',
      FreeText: 'Freetext 2',
      Checked: false,
      Checked2: true,
    },
    {
      Id: 7,
      IcdName: '',
      IcdCode: '',
      FreeText:
        'Freetext 2 more and more and more and more and more and more and more and more and more and more and more and more and more and more ',
      Checked: false,
      Checked2: true,
    },
  ],
  Prescription: [
    {
      Id: 1,
      DrugName: 'Aspirin',
      Strength: '4mg',
      DispenseUnit: 'tablets',
      Directions: 'Ngày 1 viên - Sáng',
    },
    {
      Id: 2,
      DrugName: 'Telanol',
      Strength: '4ml',
      DispenseUnit: 'capsules',
      Directions: 'Ngày 1 viên - Sáng',
    },
    {
      Id: 3,
      DrugName: 'Vitamin C',
      Strength: '1000mg',
      DispenseUnit: 'oral',
      Directions: 'Ngày 2 viên - Sáng 1 - Tối 1 (Sau ăn)',
    },
  ],
};

export const icd10s = [
  {
    Id: 1,
    Name: 'Viêm gan virus',
    NameEnglish: 'Viral hepatitis',
    Code: 'B15-B19',
  },
  {
    Id: 7,
    Name: 'Sốt virus và sốt xuất huyết virus do tiết túc truyền',
    NameEnglish: 'Arthropod-borne viral fevers and viral haemorrhagic fevers',
    Code: 'A92-A99',
  },
  {
    Id: 8,
    Name: 'Nhiễm virus ở hệ thần kinh trung ương',
    NameEnglish: 'Viral infections of the central nervous system',
    Code: 'A80-A89',
  },
  {
    Id: 9,
    Name: 'Bệnh do Rickettsia',
    NameEnglish: 'Rickettsioses',
    Code: ' A75-A79',
  },
  {
    Id: 10,
    Name: 'Các bệnh khác do Chlamydia',
    NameEnglish: 'Other diseases caused by chlamydiae',
    Code: 'A70-A74',
  },
  {
    Id: 11,
    Name: 'Bệnh do xoắn trùng khác',
    NameEnglish: 'Other spirochaetal diseases',
    Code: 'A65-A69',
  },
  {
    Id: 12,
    Name: 'Bệnh nhiễm trùng lây truyền chủ yếu qua đường tình dục',
    NameEnglish: 'Infections with a predominantly sexual mode of transmission',
    Code: 'A50-A64',
  },
  {
    Id: 13,
    Name: 'Bệnh nhiễm trùng đường ruột',
    NameEnglish: 'Intestinal infectious diseases',
    Code: 'A00-A09',
  },
  {
    Id: 14,
    Name: 'Bệnh nhiễm khuẩn do động vật truyền sang người',
    NameEnglish: 'Certain zoonotic bacterial diseases',
    Code: 'A20-A28',
  },
  {
    Id: 15,
    Name: 'Bệnh lao',
    NameEnglish: 'Tuberculosis',
    Code: 'A15-A19',
  },
];

export const chestMeasurements = [
  { Id: 1, Text: 'I' },
  { Id: 2, Text: 'II' },
  { Id: 3, Text: 'III' },
];




export const drugs = [
  {
    Id: 1,
    Name: 'Viêm gan virus',
    Strength: 'Viral hepatitis',
  },
  {
    Id: 7,
    Name: 'Sốt virus và sốt xuất huyết virus do tiết túc truyền',
    NameEnglish: 'Arthropod-borne viral fevers and viral haemorrhagic fevers',
    Code: 'A92-A99',
  },
  {
    Id: 8,
    Name: 'Nhiễm virus ở hệ thần kinh trung ương',
    NameEnglish: 'Viral infections of the central nervous system',
    Code: 'A80-A89',
  },
  {
    Id: 9,
    Name: 'Bệnh do Rickettsia',
    NameEnglish: 'Rickettsioses',
    Code: ' A75-A79',
  },
  {
    Id: 10,
    Name: 'Các bệnh khác do Chlamydia',
    NameEnglish: 'Other diseases caused by chlamydiae',
    Code: 'A70-A74',
  },
  {
    Id: 11,
    Name: 'Bệnh do xoắn trùng khác',
    NameEnglish: 'Other spirochaetal diseases',
    Code: 'A65-A69',
  },
  {
    Id: 12,
    Name: 'Bệnh nhiễm trùng lây truyền chủ yếu qua đường tình dục',
    NameEnglish: 'Infections with a predominantly sexual mode of transmission',
    Code: 'A50-A64',
  },
  {
    Id: 13,
    Name: 'Bệnh nhiễm trùng đường ruột',
    NameEnglish: 'Intestinal infectious diseases',
    Code: 'A00-A09',
  },
  {
    Id: 14,
    Name: 'Bệnh nhiễm khuẩn do động vật truyền sang người',
    NameEnglish: 'Certain zoonotic bacterial diseases',
    Code: 'A20-A28',
  },
  {
    Id: 15,
    Name: 'Bệnh lao',
    NameEnglish: 'Tuberculosis',
    Code: 'A15-A19',
  },
];