import { ReactComponent as checked } from '../../../assets/icon/checked-icon.svg';
import { ReactComponent as check } from '../../../assets/icon/check-icon.svg';
import { ReactComponent as uncheck } from '../../../assets/icon/uncheck-icon.svg';
import { ReactComponent as clear } from '../../../assets/icon/clear-icon.svg';
import { ReactComponent as add } from '../../../assets/icon/add-icon.svg';
import { ReactComponent as upload } from '../../../assets/icon/upload-icon.svg';
import { ReactComponent as image } from '../../../assets/icon/icon-image.svg';
import { ReactComponent as video } from '../../../assets/icon/icon-video.svg';
import { ReactComponent as docx } from '../../../assets/icon/icon-docx.svg';
import { ReactComponent as file } from '../../../assets/icon/icon-file.svg';
import { ReactComponent as excel } from '../../../assets/icon/icon-excel.svg';
import { ReactComponent as deleteIcon } from '../../../assets/icon/delete.svg';
import { ReactComponent as download } from '../../../assets/icon/download.svg';
import { ReactComponent as task } from '../../../assets/icon/task.svg';
import { ReactComponent as relatedDoc } from '../../../assets/icon/related-document.svg';
import { ReactComponent as report } from '../../../assets/icon/report.svg';
import { ReactComponent as pdf } from '../../../assets/icon/icon-pdf.svg';

export const CheckedIcon = checked;
export const CheckIcon = check;
export const UncheckIcon = uncheck;
export const ClearIcon = clear;
export const AddIcon = add;
export const UploadIcon = upload;
export const ImageIcon = image;
export const VideoIcon = video;
export const DocxIcon = docx;
export const FileIcon = file;
export const DeleteIcon = deleteIcon;
export const DownloadIcon = download;
export const ExcelIcon = excel;
export const TaskIcon = task;
export const RelatedDocIcon = relatedDoc;
export const ReportIcon = report;
export const PdfIcon = pdf;
